### ISSUE TITLE
GPL license not compatible with MIT

### ISSUE THREAD

**Issue by PikaMug** [RamonBlissenbach/NamelessMC-Resources-German-Translation#1]
Would you consider changing the project license to MIT so it could be included with Nameless-Resources?

**Comment by RamonBlissenbach** [comment]
I have updated the licence. :)

**Comment by PikaMug** [comment]
@RamonBlissenbach Thank you! If it's alright with you, I'll bring it to the attention of the Resources team, and include it in the next release of [Resourceful](https://github.com/Browsit/Nameless-Resourceful) for now.

**Comment by RamonBlissenbach** [comment]
Sure! :)
